### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by xXFlyingBananaXx** [kaiser-jan/scriptable-untis#1]
Im getting a weird error, ive added a screenshot with the error
![IMG_0090](https://github.com/JFK-05/scriptable-untis/assets/64354985/0f498de7-8ada-41a5-b504-6a588f5f672c)

**Comment by xXFlyingBananaXx** [comment]
Fixed the error by removimg exams grades and absences from the view since my school doesnt support that but now i just get all the lessons without the start end end time and in an unorganized way
![IMG_0091](https://github.com/JFK-05/scriptable-untis/assets/64354985/ec048505-92ac-4150-b366-300154dc9817)

**Comment by JFK-05** [comment]
Great to hear that you were able to resolve the first issue by yourself. I might handle this error whenever I find time to work on this project again.

Regarding the second problem, the "unordered" list of subjects is working as expected, and as stated in the documentation:

> After a school day has ended, a summary of the next day is displayed. (list of subjects)

Maybe this needs further explanation: After a school day has ended a preview of the next day is shown. This is meant to tell you what subjects to prepare for. Any further details about subjects are not displayed as this would simply not be possible with the limited space.

Does this resolve your issue? Are you seeing the expected view today?

**Comment by xXFlyingBananaXx** [comment]
hey yeah i now did see its organized thanks, but one last thing. When i have 2 Subjects at the same time can i show the them both in line or smth similiar bc right now it just shows the first one and the start+end time but then the second lesson but without the times, ive included two screenshots and u can see it says italienisch and then the time but on nwt it doesnt? ![image](https://github.com/JFK-05/scriptable-untis/assets/64354985/6daad36a-9076-46e6-ae65-9eba40fc0cab)![image](https://github.com/JFK-05/scriptable-untis/assets/64354985/28b4bc0a-e122-45a1-b112-5d0c0ff4d82f)

**Comment by kaiser-jan** [comment]
Sorry for not replying for an eternity! I seem to have missed the notification 😅

What you were seeing is intended behavior: If two subjects are at the same time, they get shown like this, where the start-/endtime is only shown for the first subject. The idea was to avoid showing the same timestamps twice.

What would be the behavior you expected? Showing the times twice, for "Italienisch" and "NWT"?

Regarding the idea of showing multiple subjects inline: I intentionally didn't copy this aspect of Untis, as - especially on the small widget - there simply is not enough horizontal space. However, I get that it would have advantages for larger widget sizes, as vertical space is extremely limited as well.
Currently I don't really have spare time for this project, but I might consider this in the future.

**Comment by xXFlyingBananaXx** [comment]
Uhm yea dont worry i forgot it too, it would be great if the two lessons would be displayed in the same line as in "NWT/Italienisch 10:45-11:45"
or if i could blacklist some Subjects like Italienisch since im not in the lesson for it.

**Comment by kaiser-jan** [comment]
Ok, I get that. Showing them in one line sadly is not yet possible - but blacklisting is!

Here is how:
Open the Widget Settings by running the script and selecting `Open Settings`. Go to `Subjects` and enter the exact short name of the subject, including casing. In your case it should be `IT`. Then you can click the property `Show` to toggle its visibility.
The changes should be visible after the widget refreshes, you can also preview it by selecting `Show Widget` when running the script.
