### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by CatPaulKatze** [kaiser-jan/scriptable-untis#2]
Hi,
Everytime i like to generate the Widget or update the Element Type, i get „could not Login. Please check your credentials“.
My credentials are correct. Could it maybe be because my username contains only numbers or because of the school?

I am looking forwoard for an solution! (We can also write german in this Issue)

**Comment by kaiser-jan** [comment]
Hi! Could you provide the log output when running the script from Scriptable?

Your username consisting of numbers only should most definitely not be an issue.
Differences in the login process between schools might be an issue, but that's hard to say.

Does logging in via the WebApp (https://webuntis.com) work?
Are you maybe using 2 Factor Authentication? (the script sadly doesn't support it)

I'm a little afraid the log might not help either, we'd probably have to add some log statements to the code to determine where it is failing. Sadly WebUntis isn't really open to 3rd party software (like this script), therefore the login is a little sketchy.
Also, as I have finished school, I probably won't be able to test anymore, as my account is expired :/
Maybe I should consider archiving the repository...

But still, let's try to get it to work anyway, would be great if it could help some more people :)

**Comment by CatPaulKatze** [comment]
Hi,
here are some Pictures of the Log and Popup Message:
![WhatsApp Bild 2024-09-06 um 20 06 55_6d6155d9](https://github.com/user-attachments/assets/1bfc1dcc-ecd9-446d-91ab-0699c7427f32)
![WhatsApp Bild 2024-09-06 um 20 06 53_ae3079b0](https://github.com/user-attachments/assets/5b2dd404-1def-46da-91f5-adc53c499196)

I will also investigate in the code but i didn't had the opertunity to do that.

If you like speaking over writing (like me), we also can contact us on Discord and then post the solution here in the issue! The Name is the same as my Github name

**Comment by CatPaulKatze** [comment]
There was a Problem with the characters in the password
